### ISSUE TITLE
Error Please add aws auth backend plugin after installing the plugin

### ISSUE THREAD

**Issue by tafelito** [RoadieHQ/backstage-plugin-aws-lambda#45]
## Current Behavior
I just added this plugin to my Backstage app but I'm getting `Please add aws auth backend plugin` error even though I followed the guide for both frontend and backend. The` backstage-plugin-aws-auth` docs says to use  `apiRouter.use('/aws', await aws(awsEnv));` to set up the api route and even changing it to `/aws/credentials` didn't work either

## Steps to Reproduce

1. Create a new Backstage app using `@backstage/create-app`
2. Add AWSLambda Plugin following the current docs

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): `@roadiehq/backstage-plugin-aws-lambda": "^1.0.0"`, `"@roadiehq/backstage-plugin-aws-auth": "^0.2.0",`
- Backstage version (e.g. 0.1.1-alpha23): `0.7.4`
- NodeJS Version (e.g. v12): `v14.16.1`
- Operating System and Version (e.g. Ubuntu 14.04): 
- Browser Information (e.g. chrome 85):

**Comment by Xantier** [comment]
Thanks for reporting this @tafelito! 
I've created a remediation for this on the aws-auth plugin side. We'll be releasing that later today and closing this issue with that. Let me know if there is something else blocking you on this.

**Comment by tafelito** [comment]
Thank you @Xantier for looking at this. I just updated to `"@roadiehq/backstage-plugin-aws-auth": "^0.2.1",` but I'm still seeing the same issue. Was the change included in the latest release?

**Comment by Xantier** [comment]
Hmm, we are using `aws-mfa` locally as well for these and it seems to classically 'work on my machine'. Would you mind hopping over to our Discord and we can debug this together? You can find that from link: https://discord.gg/X9hA7dRx
